'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class member
    Public Property member_name As String
    Public Property member_phone As String
    Public Property member_email As String
    Public Property member_birthday As Date
    Public Property member_point As Nullable(Of Integer)

End Class
