'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class storeEntities4
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=storeEntities4")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property member() As DbSet(Of member)
    Public Property order_management() As DbSet(Of order_management)
    Public Property products() As DbSet(Of products)
    Public Property products_material() As DbSet(Of products_material)
    Public Property purchase_records() As DbSet(Of purchase_records)
    Public Property stock() As DbSet(Of stock)
    Public Property order_current() As DbSet(Of order_current)
    Public Property order_store() As DbSet(Of order_store)

End Class
